name: CI 2025 Zig

on:
  push:
    branches:
      - master
      - "2025-zig-*"
    paths:
      - "2025/zig/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0-dev.1484+d0ba6642b

      - run: zig build test
        working-directory: ./2025/zig
