name: CI 2025 Python

on:
  push:
    branches:
      - master
      - "2025-py-*"
    paths:
      - "2025/python/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install typos
        uses: crate-ci/typos@v1.41.0
        with:
          files: ./README.md
      - name: Move typos into path
        run: mv ./typos /usr/local/bin/

      - name: Run checks
        run: just check
        working-directory: ./2025/python
